// Generated by rstantools.  Do not edit by hand.

/*
    epidp is free software: you can redistribute it and/or modify
    it under the terms of the GNU General Public License as published by
    the Free Software Foundation, either version 3 of the License, or
    (at your option) any later version.

    epidp is distributed in the hope that it will be useful,
    but WITHOUT ANY WARRANTY; without even the implied warranty of
    MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
    GNU General Public License for more details.

    You should have received a copy of the GNU General Public License
    along with epidp.  If not, see <http://www.gnu.org/licenses/>.
*/
#ifndef MODELS_HPP
#define MODELS_HPP
#define STAN__SERVICES__COMMAND_HPP
#ifndef USE_STANC3
#define USE_STANC3
#endif
#include <rstan/rstaninc.hpp>
// Code generated by stanc v2.35.0
#include <stan/model/model_header.hpp>
namespace model_epifilter_namespace {
using stan::model::model_base_crtp;
using namespace stan::math;
stan::math::profile_map profiles__;
static constexpr std::array<const char*, 41> locations_array__ =
  {" (found before start of program)",
  " (in 'epifilter', line 8, column 2 to column 23)",
  " (in 'epifilter', line 9, column 2 to column 22)",
  " (in 'epifilter', line 12, column 2 to column 20)",
  " (in 'epifilter', line 41, column 2 to column 27)",
  " (in 'epifilter', line 14, column 11 to column 15)",
  " (in 'epifilter', line 14, column 4 to column 24)",
  " (in 'epifilter', line 26, column 10 to column 31)",
  " (in 'epifilter', line 25, column 8 to line 26, column 31)",
  " (in 'epifilter', line 24, column 13 to line 27, column 7)",
  " (in 'epifilter', line 19, column 8 to column 30)",
  " (in 'epifilter', line 21, column 10 to column 31)",
  " (in 'epifilter', line 20, column 8 to line 21, column 31)",
  " (in 'epifilter', line 23, column 10 to column 32)",
  " (in 'epifilter', line 22, column 8 to line 23, column 32)",
  " (in 'epifilter', line 18, column 27 to line 24, column 7)",
  " (in 'epifilter', line 18, column 13 to line 27, column 7)",
  " (in 'epifilter', line 17, column 8 to column 37)",
  " (in 'epifilter', line 16, column 17 to line 18, column 7)",
  " (in 'epifilter', line 16, column 6 to line 27, column 7)",
  " (in 'epifilter', line 28, column 6 to column 37)",
  " (in 'epifilter', line 15, column 18 to line 29, column 5)",
  " (in 'epifilter', line 15, column 4 to line 29, column 5)",
  " (in 'epifilter', line 13, column 2 to line 30, column 3)",
  " (in 'epifilter', line 43, column 4 to column 54)",
  " (in 'epifilter', line 42, column 2 to line 43, column 54)",
  " (in 'epifilter', line 34, column 4 to column 31)",
  " (in 'epifilter', line 35, column 4 to column 48)",
  " (in 'epifilter', line 33, column 16 to line 36, column 3)",
  " (in 'epifilter', line 33, column 2 to line 36, column 3)",
  " (in 'epifilter', line 37, column 2 to column 24)",
  " (in 'epifilter', line 38, column 2 to column 23)",
  " (in 'epifilter', line 2, column 2 to column 8)",
  " (in 'epifilter', line 3, column 8 to column 9)",
  " (in 'epifilter', line 3, column 2 to column 17)",
  " (in 'epifilter', line 4, column 2 to column 11)",
  " (in 'epifilter', line 5, column 13 to column 17)",
  " (in 'epifilter', line 5, column 2 to column 21)",
  " (in 'epifilter', line 8, column 18 to column 19)",
  " (in 'epifilter', line 12, column 9 to column 10)",
  " (in 'epifilter', line 41, column 9 to column 10)"};
#include <stan_meta_header.hpp>
class model_epifilter final : public model_base_crtp<model_epifilter> {
private:
  int N;
  std::vector<int> C;
  int wmax;
  Eigen::Matrix<double,1,-1> w_data__;
  Eigen::Map<Eigen::Matrix<double,1,-1>> w{nullptr, 0};
public:
  ~model_epifilter() {}
  model_epifilter(stan::io::var_context& context__, unsigned int
                  random_seed__ = 0, std::ostream* pstream__ = nullptr)
      : model_base_crtp(0) {
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    using local_scalar_t__ = double;
    auto base_rng__ = stan::services::util::create_rng(random_seed__, 0);
    // suppress unused var warning
    (void) base_rng__;
    static constexpr const char* function__ =
      "model_epifilter_namespace::model_epifilter";
    // suppress unused var warning
    (void) function__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      current_statement__ = 32;
      context__.validate_dims("data initialization", "N", "int",
        std::vector<size_t>{});
      N = std::numeric_limits<int>::min();
      current_statement__ = 32;
      N = context__.vals_i("N")[(1 - 1)];
      current_statement__ = 33;
      stan::math::validate_non_negative_index("C", "N", N);
      current_statement__ = 34;
      context__.validate_dims("data initialization", "C", "int",
        std::vector<size_t>{static_cast<size_t>(N)});
      C = std::vector<int>(N, std::numeric_limits<int>::min());
      current_statement__ = 34;
      C = context__.vals_i("C");
      current_statement__ = 35;
      context__.validate_dims("data initialization", "wmax", "int",
        std::vector<size_t>{});
      wmax = std::numeric_limits<int>::min();
      current_statement__ = 35;
      wmax = context__.vals_i("wmax")[(1 - 1)];
      current_statement__ = 36;
      stan::math::validate_non_negative_index("w", "wmax", wmax);
      current_statement__ = 37;
      context__.validate_dims("data initialization", "w", "double",
        std::vector<size_t>{static_cast<size_t>(wmax)});
      w_data__ = Eigen::Matrix<double,1,-1>::Constant(wmax,
                   std::numeric_limits<double>::quiet_NaN());
      new (&w) Eigen::Map<Eigen::Matrix<double,1,-1>>(w_data__.data(), wmax);
      {
        std::vector<local_scalar_t__> w_flat__;
        current_statement__ = 37;
        w_flat__ = context__.vals_r("w");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= wmax; ++sym1__) {
          stan::model::assign(w, w_flat__[(pos__ - 1)],
            "assigning variable w", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      current_statement__ = 38;
      stan::math::validate_non_negative_index("R", "N", N);
      current_statement__ = 39;
      stan::math::validate_non_negative_index("E_cases", "N", N);
      current_statement__ = 40;
      stan::math::validate_non_negative_index("log_likelihood", "N", N);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    num_params_r__ = N + 1;
  }
  inline std::string model_name() const final {
    return "model_epifilter";
  }
  inline std::vector<std::string> model_compile_info() const noexcept {
    return std::vector<std::string>{"stanc_version = stanc3 v2.35.0",
             "stancflags = --allow-undefined"};
  }
  // Base log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_not_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_epifilter_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> R =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 1;
      R = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, N);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> E_cases =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        current_statement__ = 5;
        stan::math::validate_non_negative_index("I_temp", "wmax", wmax);
        Eigen::Matrix<local_scalar_t__,-1,1> I_temp =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(wmax, DUMMY_VAR__);
        current_statement__ = 22;
        for (int t = 1; t <= N; ++t) {
          current_statement__ = 19;
          if (stan::math::logical_eq(t, 1)) {
            current_statement__ = 17;
            stan::model::assign(I_temp, stan::math::rep_vector(0, wmax),
              "assigning variable I_temp");
          } else {
            current_statement__ = 16;
            if (stan::math::logical_lte(t, wmax)) {
              int kk = std::numeric_limits<int>::min();
              current_statement__ = 10;
              kk = ((wmax - t) + 1);
              current_statement__ = 12;
              for (int i = 1; i <= (t - 1); ++i) {
                current_statement__ = 11;
                stan::model::assign(I_temp,
                  stan::model::rvalue(C, "C", stan::model::index_uni((t - i))),
                  "assigning variable I_temp", stan::model::index_uni(i));
              }
              current_statement__ = 14;
              for (int i = 1; i <= kk; ++i) {
                current_statement__ = 13;
                stan::model::assign(I_temp, 0, "assigning variable I_temp",
                  stan::model::index_uni(((i + t) - 1)));
              }
            } else {
              current_statement__ = 8;
              for (int i = 1; i <= wmax; ++i) {
                current_statement__ = 7;
                stan::model::assign(I_temp,
                  stan::model::rvalue(C, "C", stan::model::index_uni((t - i))),
                  "assigning variable I_temp", stan::model::index_uni(i));
              }
            }
          }
          current_statement__ = 20;
          stan::model::assign(E_cases,
            stan::math::multiply(
              stan::math::multiply(
                stan::model::rvalue(R, "R", stan::model::index_uni(t)), w),
              I_temp), "assigning variable E_cases",
            stan::model::index_uni(t));
        }
      }
      {
        current_statement__ = 29;
        for (int t = 2; t <= N; ++t) {
          current_statement__ = 26;
          lp_accum__.add(stan::math::poisson_lpmf<propto__>(
                           stan::model::rvalue(C, "C",
                             stan::model::index_uni(t)),
                           stan::model::rvalue(E_cases, "E_cases",
                             stan::model::index_uni(t))));
          current_statement__ = 27;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni(t)),
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni((t - 1))), (sigma *
                           stan::math::sqrt(
                             stan::model::rvalue(R, "R",
                               stan::model::index_uni(t))))));
        }
        current_statement__ = 30;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                         stan::model::rvalue(R, "R",
                           stan::model::index_uni(1)), 0, 50));
        current_statement__ = 31;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma, 0, 1));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  // Reverse mode autodiff log prob
  template <bool propto__, bool jacobian__, typename VecR, typename VecI,
            stan::require_vector_like_t<VecR>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr,
            stan::require_st_var<VecR>* = nullptr>
  inline stan::scalar_type_t<VecR>
  log_prob_impl(VecR& params_r__, VecI& params_i__, std::ostream*
                pstream__ = nullptr) const {
    using T__ = stan::scalar_type_t<VecR>;
    using local_scalar_t__ = T__;
    T__ lp__(0.0);
    stan::math::accumulator<T__> lp_accum__;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    static constexpr const char* function__ =
      "model_epifilter_namespace::log_prob";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> R =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 1;
      R = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, N);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<local_scalar_t__,-1,1> E_cases =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        current_statement__ = 5;
        stan::math::validate_non_negative_index("I_temp", "wmax", wmax);
        Eigen::Matrix<local_scalar_t__,-1,1> I_temp =
          Eigen::Matrix<local_scalar_t__,-1,1>::Constant(wmax, DUMMY_VAR__);
        current_statement__ = 22;
        for (int t = 1; t <= N; ++t) {
          current_statement__ = 19;
          if (stan::math::logical_eq(t, 1)) {
            current_statement__ = 17;
            stan::model::assign(I_temp, stan::math::rep_vector(0, wmax),
              "assigning variable I_temp");
          } else {
            current_statement__ = 16;
            if (stan::math::logical_lte(t, wmax)) {
              int kk = std::numeric_limits<int>::min();
              current_statement__ = 10;
              kk = ((wmax - t) + 1);
              current_statement__ = 12;
              for (int i = 1; i <= (t - 1); ++i) {
                current_statement__ = 11;
                stan::model::assign(I_temp,
                  stan::model::rvalue(C, "C", stan::model::index_uni((t - i))),
                  "assigning variable I_temp", stan::model::index_uni(i));
              }
              current_statement__ = 14;
              for (int i = 1; i <= kk; ++i) {
                current_statement__ = 13;
                stan::model::assign(I_temp, 0, "assigning variable I_temp",
                  stan::model::index_uni(((i + t) - 1)));
              }
            } else {
              current_statement__ = 8;
              for (int i = 1; i <= wmax; ++i) {
                current_statement__ = 7;
                stan::model::assign(I_temp,
                  stan::model::rvalue(C, "C", stan::model::index_uni((t - i))),
                  "assigning variable I_temp", stan::model::index_uni(i));
              }
            }
          }
          current_statement__ = 20;
          stan::model::assign(E_cases,
            stan::math::multiply(
              stan::math::multiply(
                stan::model::rvalue(R, "R", stan::model::index_uni(t)), w),
              I_temp), "assigning variable E_cases",
            stan::model::index_uni(t));
        }
      }
      {
        current_statement__ = 29;
        for (int t = 2; t <= N; ++t) {
          current_statement__ = 26;
          lp_accum__.add(stan::math::poisson_lpmf<propto__>(
                           stan::model::rvalue(C, "C",
                             stan::model::index_uni(t)),
                           stan::model::rvalue(E_cases, "E_cases",
                             stan::model::index_uni(t))));
          current_statement__ = 27;
          lp_accum__.add(stan::math::normal_lpdf<propto__>(
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni(t)),
                           stan::model::rvalue(R, "R",
                             stan::model::index_uni((t - 1))), (sigma *
                           stan::math::sqrt(
                             stan::model::rvalue(R, "R",
                               stan::model::index_uni(t))))));
        }
        current_statement__ = 30;
        lp_accum__.add(stan::math::uniform_lpdf<propto__>(
                         stan::model::rvalue(R, "R",
                           stan::model::index_uni(1)), 0, 50));
        current_statement__ = 31;
        lp_accum__.add(stan::math::cauchy_lpdf<propto__>(sigma, 0, 1));
      }
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
    lp_accum__.add(lp__);
    return lp_accum__.sum();
  }
  template <typename RNG, typename VecR, typename VecI, typename VecVar,
            stan::require_vector_like_vt<std::is_floating_point,
            VecR>* = nullptr, stan::require_vector_like_vt<std::is_integral,
            VecI>* = nullptr, stan::require_vector_vt<std::is_floating_point,
            VecVar>* = nullptr>
  inline void
  write_array_impl(RNG& base_rng__, VecR& params_r__, VecI& params_i__,
                   VecVar& vars__, const bool
                   emit_transformed_parameters__ = true, const bool
                   emit_generated_quantities__ = true, std::ostream*
                   pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    static constexpr bool propto__ = true;
    // suppress unused var warning
    (void) propto__;
    double lp__ = 0.0;
    // suppress unused var warning
    (void) lp__;
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    stan::math::accumulator<double> lp_accum__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    constexpr bool jacobian__ = false;
    // suppress unused var warning
    (void) jacobian__;
    static constexpr const char* function__ =
      "model_epifilter_namespace::write_array";
    // suppress unused var warning
    (void) function__;
    try {
      Eigen::Matrix<double,-1,1> R =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 1;
      R = in__.template read_constrain_lb<
            Eigen::Matrix<local_scalar_t__,-1,1>, jacobian__>(0, lp__, N);
      double sigma = std::numeric_limits<double>::quiet_NaN();
      current_statement__ = 2;
      sigma = in__.template read_constrain_lb<local_scalar_t__,
                jacobian__>(0, lp__);
      Eigen::Matrix<double,-1,1> E_cases =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      out__.write(R);
      out__.write(sigma);
      if (stan::math::logical_negation(
            (stan::math::primitive_value(emit_transformed_parameters__) ||
            stan::math::primitive_value(emit_generated_quantities__)))) {
        return ;
      }
      {
        current_statement__ = 5;
        stan::math::validate_non_negative_index("I_temp", "wmax", wmax);
        Eigen::Matrix<double,-1,1> I_temp =
          Eigen::Matrix<double,-1,1>::Constant(wmax,
            std::numeric_limits<double>::quiet_NaN());
        current_statement__ = 22;
        for (int t = 1; t <= N; ++t) {
          current_statement__ = 19;
          if (stan::math::logical_eq(t, 1)) {
            current_statement__ = 17;
            stan::model::assign(I_temp, stan::math::rep_vector(0, wmax),
              "assigning variable I_temp");
          } else {
            current_statement__ = 16;
            if (stan::math::logical_lte(t, wmax)) {
              int kk = std::numeric_limits<int>::min();
              current_statement__ = 10;
              kk = ((wmax - t) + 1);
              current_statement__ = 12;
              for (int i = 1; i <= (t - 1); ++i) {
                current_statement__ = 11;
                stan::model::assign(I_temp,
                  stan::model::rvalue(C, "C", stan::model::index_uni((t - i))),
                  "assigning variable I_temp", stan::model::index_uni(i));
              }
              current_statement__ = 14;
              for (int i = 1; i <= kk; ++i) {
                current_statement__ = 13;
                stan::model::assign(I_temp, 0, "assigning variable I_temp",
                  stan::model::index_uni(((i + t) - 1)));
              }
            } else {
              current_statement__ = 8;
              for (int i = 1; i <= wmax; ++i) {
                current_statement__ = 7;
                stan::model::assign(I_temp,
                  stan::model::rvalue(C, "C", stan::model::index_uni((t - i))),
                  "assigning variable I_temp", stan::model::index_uni(i));
              }
            }
          }
          current_statement__ = 20;
          stan::model::assign(E_cases,
            stan::math::multiply(
              stan::math::multiply(
                stan::model::rvalue(R, "R", stan::model::index_uni(t)), w),
              I_temp), "assigning variable E_cases",
            stan::model::index_uni(t));
        }
      }
      if (emit_transformed_parameters__) {
        out__.write(E_cases);
      }
      if (stan::math::logical_negation(emit_generated_quantities__)) {
        return ;
      }
      Eigen::Matrix<double,-1,1> log_likelihood =
        Eigen::Matrix<double,-1,1>::Constant(N,
          std::numeric_limits<double>::quiet_NaN());
      current_statement__ = 25;
      for (int t = 1; t <= N; ++t) {
        current_statement__ = 24;
        stan::model::assign(log_likelihood,
          stan::math::poisson_lpmf<false>(
            stan::model::rvalue(C, "C", stan::model::index_uni(t)),
            stan::model::rvalue(E_cases, "E_cases", stan::model::index_uni(t))),
          "assigning variable log_likelihood", stan::model::index_uni(t));
      }
      out__.write(log_likelihood);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, typename VecI,
            stan::require_vector_t<VecVar>* = nullptr,
            stan::require_vector_like_vt<std::is_integral, VecI>* = nullptr>
  inline void
  unconstrain_array_impl(const VecVar& params_r__, const VecI& params_i__,
                         VecVar& vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::deserializer<local_scalar_t__> in__(params_r__, params_i__);
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      Eigen::Matrix<local_scalar_t__,-1,1> R =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      current_statement__ = 1;
      stan::model::assign(R,
        in__.read<Eigen::Matrix<local_scalar_t__,-1,1>>(N),
        "assigning variable R");
      out__.write_free_lb(0, R);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = in__.read<local_scalar_t__>();
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  template <typename VecVar, stan::require_vector_t<VecVar>* = nullptr>
  inline void
  transform_inits_impl(const stan::io::var_context& context__, VecVar&
                       vars__, std::ostream* pstream__ = nullptr) const {
    using local_scalar_t__ = double;
    stan::io::serializer<local_scalar_t__> out__(vars__);
    int current_statement__ = 0;
    // suppress unused var warning
    (void) current_statement__;
    local_scalar_t__ DUMMY_VAR__(std::numeric_limits<double>::quiet_NaN());
    // suppress unused var warning
    (void) DUMMY_VAR__;
    try {
      current_statement__ = 1;
      context__.validate_dims("parameter initialization", "R", "double",
        std::vector<size_t>{static_cast<size_t>(N)});
      current_statement__ = 2;
      context__.validate_dims("parameter initialization", "sigma", "double",
        std::vector<size_t>{});
      int pos__ = std::numeric_limits<int>::min();
      pos__ = 1;
      Eigen::Matrix<local_scalar_t__,-1,1> R =
        Eigen::Matrix<local_scalar_t__,-1,1>::Constant(N, DUMMY_VAR__);
      {
        std::vector<local_scalar_t__> R_flat__;
        current_statement__ = 1;
        R_flat__ = context__.vals_r("R");
        pos__ = 1;
        for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
          stan::model::assign(R, R_flat__[(pos__ - 1)],
            "assigning variable R", stan::model::index_uni(sym1__));
          pos__ = (pos__ + 1);
        }
      }
      out__.write_free_lb(0, R);
      local_scalar_t__ sigma = DUMMY_VAR__;
      current_statement__ = 2;
      sigma = context__.vals_r("sigma")[(1 - 1)];
      out__.write_free_lb(0, sigma);
    } catch (const std::exception& e) {
      stan::lang::rethrow_located(e, locations_array__[current_statement__]);
    }
  }
  inline void
  get_param_names(std::vector<std::string>& names__, const bool
                  emit_transformed_parameters__ = true, const bool
                  emit_generated_quantities__ = true) const {
    names__ = std::vector<std::string>{"R", "sigma"};
    if (emit_transformed_parameters__) {
      std::vector<std::string> temp{"E_cases"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::string> temp{"log_likelihood"};
      names__.reserve(names__.size() + temp.size());
      names__.insert(names__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  get_dims(std::vector<std::vector<size_t>>& dimss__, const bool
           emit_transformed_parameters__ = true, const bool
           emit_generated_quantities__ = true) const {
    dimss__ = std::vector<std::vector<size_t>>{std::vector<size_t>{static_cast<
                                                                    size_t>(N)},
                std::vector<size_t>{}};
    if (emit_transformed_parameters__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
    if (emit_generated_quantities__) {
      std::vector<std::vector<size_t>>
        temp{std::vector<size_t>{static_cast<size_t>(N)}};
      dimss__.reserve(dimss__.size() + temp.size());
      dimss__.insert(dimss__.end(), temp.begin(), temp.end());
    }
  }
  inline void
  constrained_param_names(std::vector<std::string>& param_names__, bool
                          emit_transformed_parameters__ = true, bool
                          emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "R" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "E_cases" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_likelihood" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline void
  unconstrained_param_names(std::vector<std::string>& param_names__, bool
                            emit_transformed_parameters__ = true, bool
                            emit_generated_quantities__ = true) const final {
    for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
      param_names__.emplace_back(std::string() + "R" + '.' +
        std::to_string(sym1__));
    }
    param_names__.emplace_back(std::string() + "sigma");
    if (emit_transformed_parameters__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "E_cases" + '.' +
          std::to_string(sym1__));
      }
    }
    if (emit_generated_quantities__) {
      for (int sym1__ = 1; sym1__ <= N; ++sym1__) {
        param_names__.emplace_back(std::string() + "log_likelihood" + '.' +
          std::to_string(sym1__));
      }
    }
  }
  inline std::string get_constrained_sizedtypes() const {
    return std::string("[{\"name\":\"R\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"E_cases\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_likelihood\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  inline std::string get_unconstrained_sizedtypes() const {
    return std::string("[{\"name\":\"R\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"parameters\"},{\"name\":\"sigma\",\"type\":{\"name\":\"real\"},\"block\":\"parameters\"},{\"name\":\"E_cases\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"transformed_parameters\"},{\"name\":\"log_likelihood\",\"type\":{\"name\":\"vector\",\"length\":" + std::to_string(N) + "},\"block\":\"generated_quantities\"}]");
  }
  // Begin method overload boilerplate
  template <typename RNG> inline void
  write_array(RNG& base_rng, Eigen::Matrix<double,-1,1>& params_r,
              Eigen::Matrix<double,-1,1>& vars, const bool
              emit_transformed_parameters = true, const bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (N + 1);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    std::vector<int> params_i;
    vars = Eigen::Matrix<double,-1,1>::Constant(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <typename RNG> inline void
  write_array(RNG& base_rng, std::vector<double>& params_r, std::vector<int>&
              params_i, std::vector<double>& vars, bool
              emit_transformed_parameters = true, bool
              emit_generated_quantities = true, std::ostream*
              pstream = nullptr) const {
    const size_t num_params__ = (N + 1);
    const size_t num_transformed = emit_transformed_parameters * (N);
    const size_t num_gen_quantities = emit_generated_quantities * (N);
    const size_t num_to_write = num_params__ + num_transformed +
      num_gen_quantities;
    vars = std::vector<double>(num_to_write,
             std::numeric_limits<double>::quiet_NaN());
    write_array_impl(base_rng, params_r, params_i, vars,
      emit_transformed_parameters, emit_generated_quantities, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(Eigen::Matrix<T_,-1,1>& params_r, std::ostream* pstream = nullptr) const {
    Eigen::Matrix<int,-1,1> params_i;
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  template <bool propto__, bool jacobian__, typename T_> inline T_
  log_prob(std::vector<T_>& params_r, std::vector<int>& params_i,
           std::ostream* pstream = nullptr) const {
    return log_prob_impl<propto__, jacobian__>(params_r, params_i, pstream);
  }
  inline void
  transform_inits(const stan::io::var_context& context,
                  Eigen::Matrix<double,-1,1>& params_r, std::ostream*
                  pstream = nullptr) const final {
    std::vector<double> params_r_vec(params_r.size());
    std::vector<int> params_i;
    transform_inits(context, params_i, params_r_vec, pstream);
    params_r = Eigen::Map<Eigen::Matrix<double,-1,1>>(params_r_vec.data(),
                 params_r_vec.size());
  }
  inline void
  transform_inits(const stan::io::var_context& context, std::vector<int>&
                  params_i, std::vector<double>& vars, std::ostream*
                  pstream__ = nullptr) const {
    vars.resize(num_params_r__);
    transform_inits_impl(context, vars, pstream__);
  }
  inline void
  unconstrain_array(const std::vector<double>& params_constrained,
                    std::vector<double>& params_unconstrained, std::ostream*
                    pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = std::vector<double>(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
  inline void
  unconstrain_array(const Eigen::Matrix<double,-1,1>& params_constrained,
                    Eigen::Matrix<double,-1,1>& params_unconstrained,
                    std::ostream* pstream = nullptr) const {
    const std::vector<int> params_i;
    params_unconstrained = Eigen::Matrix<double,-1,1>::Constant(num_params_r__,
                             std::numeric_limits<double>::quiet_NaN());
    unconstrain_array_impl(params_constrained, params_i,
      params_unconstrained, pstream);
  }
};
}
using stan_model = model_epifilter_namespace::model_epifilter;
#ifndef USING_R
// Boilerplate
stan::model::model_base&
new_model(stan::io::var_context& data_context, unsigned int seed,
          std::ostream* msg_stream) {
  stan_model* m = new stan_model(data_context, seed, msg_stream);
  return *m;
}
stan::math::profile_map& get_stan_profile_data() {
  return model_epifilter_namespace::profiles__;
}
#endif
#endif
